spring:
  profiles:
    active: dev
  data:
    mongodb:
      option:
        address: ['$mongodbAddress']
        database: $mongodbDatabase
        username: $mongodbUsername
        password: $mongodbPassword
system:
  properties:
    profileActive: dev
