spring:
  profiles:
    active: dev
  data:
    mongodb:
      option:
        address: [ '120.132.18.250:27017' ]
        database: github-ams
        username: whcj
        password: LYyVKh7spO7hzDLv

system:
  properties:
    profileActive: dev
